[tool.poetry]
name = "lnd_pyshell"
version = "0.1.0"
description = ""
authors = ["Kornpow <test@email.com>"]

[tool.poetry.dependencies]
python = ">=3.6.1"
requests = "^2.24.0"
pandas = "^1.1.2"


[tool.poetry.dev-dependencies]
pytest = "^3.4"